language: java
sudo: false
install: true

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    - $HOME/.gradle

script:
  - ./gradlew sonarqube -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN

after_success:
  - ./gradlew bintrayUpload gitPublishPush -Dorg.ajoberstar.grgit.auth.username=$GIT_NAME

before_deploy:
  - git config --local user.name $GIT_NAME
  - git config --local user.email $GIT_EMAIL
  - ./gradlew assembleDist

deploy:
  provider: releases
  api_key: $GRGIT_USER
  file:
    - $TRAVIS_BUILD_DIR/build/distributions/insynsregistret*.zip
    - $TRAVIS_BUILD_DIR/build/distributions/insynsregistret*.tar.gz
  skip_cleanup: true
  on:
    tags: true
